---
# tasks file for ansible-dynu-updater

- name: Create base directory for Dynu IP updater
  file:
    path: "{{ dynu_base_dir }}"
    state: directory
    mode: 0755

- name: Generate docker compose file
  template:
    src: docker-compose.yml.j2
    dest: "{{ dynu_base_dir }}/docker-compose.yml"
    mode: 0644

- name: Run docker compose to start containers
  become: true
  community.docker.docker_compose_v2:
    project_src: "{{ dynu_base_dir }}"
    state: present
